Repository MasonHollo/Windbnb, pull requests merged in 2025-02, with the labels that each got.

#36 Auth setup
  backend/app.js
  backend/db/migrations/01-users.js
  backend/db/models/user.js
  backend/db/seeders/01-user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/api/index.js
  backend/routes/index.js
  backend/utils/auth.js
Labels: documentation

#37 phase 4 push
  backend/app.js
  backend/db/migrations/01-users.js
  backend/db/models/user.js
  backend/db/seeders/01-user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/api/index.js
  backend/routes/api/session.js
  backend/routes/api/users.js
  backend/routes/index.js
  backend/utils/auth.js
  package-lock.json
Labels: documentation

#38 Finished up phase 4
  backend/routes/api/index.js
  backend/routes/api/session.js
  backend/routes/api/users.js
  package-lock.json
Labels: documentation

#39 Auth me phase 5 completed
  backend/db/migrations/01-users.js
  backend/db/models/user.js
  backend/routes/api/index.js
  backend/routes/api/session.js
  backend/routes/api/users.js
  backend/utils/validation.js
Labels: documentation

#40 stating to main for deployment
  backend/db/migrations/01-users.js
  backend/db/models/user.js
  backend/routes/api/index.js
  backend/routes/api/session.js
  backend/routes/api/users.js
  backend/utils/validation.js
Labels: documentation

#41 added scrips for deployment
  package.json
Labels: documentation

#42 removed comment that caused issues deploying
  backend/psql-setup-script.js
Labels: documentation

#43 fixed seeding error
  backend/db/migrations/user.js
  backend/db/models/01-user.js
  backend/db/seeders/01-user.js
  backend/routes/api/index.js
Labels: documentation

#44 fixed namming issue
  backend/db/migrations/01-user.js
Labels: documentation

#45 changing name for migrations
  backend/db/migrations/01-users.js
Labels: documentation

#46 added express-validator
  backend/package-lock.json
  backend/package.json
Labels: documentation

#51 mina-updated
  backend/backup.sql
  backend/db/migrations/03-review.js
  backend/db/models/03-review.js
  backend/db/seeders/03-reviews.js
  backend/routes/api/index.js
  backend/routes/api/reviews.js
Labels: help wanted

#50 fixed get spots by current user
  backend/routes/api/session.js
  backend/routes/api/spots.js
Labels: enhancement

#52 Spot-Delete-added
  backend/routes/api/spots.js
Labels: good first issue

#53 Edit-Spot-Done
  backend/routes/api/spots.js
Labels: good first issue

#54 mk-updated-bookings
  backend/db/migrations/04-booking.js
  backend/db/models/04-booking.js
  backend/db/seeders/04-bookings.js
  backend/routes/api/bookings.js
  backend/routes/api/index.js
Labels: help wanted

#57 added try catches, changed error results, and returns to match closer to api docs
  backend/db/migrations/02-spots.js
  backend/db/migrations/03-review.js
  backend/db/migrations/05-spotImages.js
  backend/db/migrations/06-reviewImages.js
  backend/db/models/02-spot.js
  backend/db/models/03-review.js
  backend/db/models/05-spotImage.js
  backend/db/models/06-reviewImage.js
  backend/db/seeders/01-user.js
  backend/db/seeders/02-spot.js
  backend/db/seeders/05-spotImages.js
  backend/db/seeders/06-reviewImages.js
  backend/routes/api/bookings.js
  backend/routes/api/index.js
  backend/routes/api/reviews.js
  backend/routes/api/session.js
  backend/routes/api/spots.js
  backend/routes/api/users.js
  backend/utils/validation.js
Labels: enhancement

#56 Routes for delete spot-image&review-image
  backend/db/migrations/05-spotImages.js
  backend/db/migrations/06-reviewImages.js
  backend/db/models/05-spotImage.js
  backend/db/models/06-reviewImage.js
  backend/db/seeders/05-spotImages.js
  backend/db/seeders/06-reviewImages.js
  backend/routes/api/index.js
Labels: enhancement

#59 moving to main
  backend/app.js
  backend/backup.sql
  backend/db/migrations/02-spots.js
  backend/db/migrations/03-review.js
  backend/db/migrations/04-booking.js
  backend/db/migrations/05-spotImages.js
  backend/db/migrations/06-reviewImages.js
  backend/db/models/02-spot.js
  backend/db/models/03-review.js
  backend/db/models/04-booking.js
  backend/db/models/05-spotImage.js
  backend/db/models/06-reviewImage.js
  backend/db/seeders/01-user.js
  backend/db/seeders/02-spot.js
  backend/db/seeders/03-reviews.js
  backend/db/seeders/04-bookings.js
  backend/db/seeders/05-spotImages.js
  backend/db/seeders/06-reviewImages.js
  backend/routes/api/bookings.js
  backend/routes/api/index.js
  backend/routes/api/reviews.js
  backend/routes/api/session.js
  backend/routes/api/spots.js
  backend/routes/api/users.js
  backend/routes/index.js
  backend/utils/validation.js
Labels: good first issue

#60 fix for deploy
  backend/db/migrations/02-spots.js
  backend/routes/api/bookings.js
Labels: fix

#62 fix for deploy
  backend/db/migrations/02-spots.js
  backend/db/models/02-spot.js
Labels: fix

#72 fix for deploy
  backend/db/models/02-spot.js
Labels: fix

#73 fix for deploy
  backend/db/migrations/02-spots.js
Labels: fix

#74 fix for deploy
  backend/db/migrations/02-spots.js
  backend/db/migrations/03-review.js
  backend/db/migrations/04-booking.js
  backend/db/migrations/05-spotImages.js
  backend/db/migrations/06-reviewImages.js
  backend/db/models/02-spot.js
  backend/db/models/03-review.js
  backend/db/models/05-spotImage.js
  backend/db/models/06-reviewImage.js
Labels: fix

#75 fix for deploy
  backend/db/migrations/02-spots.js
  backend/db/models/02-spot.js
Labels: fix

#76 fix for deploy
  backend/db/models/03-review.js
  backend/db/models/05-spotImage.js
Labels: bug

#77 test for deploy
  backend/db/migrations/03-review.js
Labels: bug

#78 test for deploy
  backend/db/migrations/02-spots.js
  backend/db/migrations/03-review.js
  backend/db/models/02-spot.js
Labels: bug

#80 test for deploy
  backend/db/models/03-review.js
  backend/db/models/05-spotImage.js
  backend/db/models/06-reviewImage.js
Labels: bug

#81 test
  backend/db/migrations/03-reviews.js
  backend/db/migrations/04-bookings.js
  backend/db/seeders/03-reviews.js
Labels: bug

#82 testing deploy
  backend/db/models/06-reviewImage.js
Labels: bug

#83 testing
  backend/db/migrations/06-reviewImages.js
Labels: bug

#84 testing
  backend/db/migrations/03-reviews.js
  backend/db/migrations/06-reviewImages.js
  backend/db/seeders/03-reviews.js
Labels: bug

#85 testing
  backend/db/models/06-reviewImage.js
Labels: bug

#86 testing
  backend/db/models/06-reviewImage.js
Labels: bug

#87 testing
  backend/db/migrations/06-reviewImages.js
  backend/db/models/06-reviewImage.js
Labels: bug

#88 testing
  backend/db/migrations/03-reviews.js
Labels: bug

#89 testing
  backend/db/migrations/03-reviews.js
Labels: bug

#90 testing
  backend/db/migrations/06-reviewImages.js
  backend/db/models/06-reviewImage.js
Labels: bug

#91 testing
  backend/db/models/05-spotImage.js
  backend/db/seeders/03-reviews.js
  backend/db/seeders/05-spotImages.js
Labels: bug

#93 fix for get all spots
  backend/routes/api/spots.js
Labels: fix

#94 fixed some error messages
  backend/app.js
  backend/db/seeders/01-user.js
  backend/routes/api/spots.js
  backend/routes/api/users.js
  backend/utils/validation.js
Labels: fix

#95 adjusted code add and adjusted natasha code fix some error codes
  backend/routes/api/bookings.js
  backend/routes/api/spots.js
Labels: fix

#96 adjusted some errors
  backend/db/seeders/05-spotImages.js
  backend/routes/api/bookings.js
  backend/routes/api/index.js
  backend/routes/api/reviews.js
  backend/routes/api/session.js
  backend/routes/api/spots.js
  backend/utils/auth.js
Labels: fix

#97 more error messages adjusting and validations
  backend/routes/api/bookings.js
  backend/routes/api/reviews.js
  backend/routes/api/session.js
  backend/routes/api/spots.js
  backend/routes/api/users.js
Labels: fix

#98 more error messages fixes
  backend/routes/api/reviews.js
  backend/routes/api/spots.js
Labels: fix

#99 fixed a status code
  backend/routes/api/bookings.js
Labels: fix
